# Generated by Django 2.2 on 2020-10-30 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdministradorTorneos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SemiFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministradorTorneos.Game')),
            ],
        ),
        migrations.CreateModel(
            name='SemiMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('match_map', models.CharField(max_length=30)),
                ('winning_score', models.PositiveIntegerField()),
                ('losing_score', models.PositiveIntegerField()),
                ('loser', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='semimatch_loser', to='AdministradorTorneos.Player')),
                ('match_players', models.ManyToManyField(to='AdministradorTorneos.Player')),
                ('semiFinal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministradorTorneos.SemiFinal')),
                ('winner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='semimatch_winner', to='AdministradorTorneos.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='semifinal',
            name='tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdministradorTorneos.Tournament'),
        ),
        migrations.CreateModel(
            name='QuarterMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('match_map', models.CharField(max_length=30)),
                ('winning_score', models.PositiveIntegerField()),
                ('losing_score', models.PositiveIntegerField()),
                ('loser', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quartermatch_loser', to='AdministradorTorneos.Player')),
                ('match_players', models.ManyToManyField(to='AdministradorTorneos.Player')),
                ('quarterFinal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministradorTorneos.QuarterFinal')),
                ('winner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quartermatch_winner', to='AdministradorTorneos.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quarterfinal',
            name='tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdministradorTorneos.Tournament'),
        ),
        migrations.CreateModel(
            name='FinalMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('match_map', models.CharField(max_length=30)),
                ('winning_score', models.PositiveIntegerField()),
                ('losing_score', models.PositiveIntegerField()),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministradorTorneos.Final')),
                ('loser', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='finalmatch_loser', to='AdministradorTorneos.Player')),
                ('match_players', models.ManyToManyField(to='AdministradorTorneos.Player')),
                ('winner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='finalmatch_winner', to='AdministradorTorneos.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='final',
            name='tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdministradorTorneos.Tournament'),
        ),
    ]
