# Generated by Django 2.2 on 2020-11-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministradorTorneos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmatch',
            name='match_map',
            field=models.CharField(default='TBD', max_length=30),
        ),
        migrations.AlterField(
            model_name='quartermatch',
            name='match_map',
            field=models.CharField(default='TBD', max_length=30),
        ),
        migrations.AlterField(
            model_name='semimatch',
            name='match_map',
            field=models.CharField(default='TBD', max_length=30),
        ),
    ]
