# Generated by Django 2.2 on 2020-11-02 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdministradorTorneos', '0002_auto_20201102_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalmatch',
            old_name='final',
            new_name='tournament',
        ),
    ]
