# Generated by Django 2.2 on 2020-10-31 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdministradorTorneos', '0002_auto_20201030_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalmatch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quartermatch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='semimatch',
            name='name',
        ),
    ]
