# Generated by Django 2.2 on 2020-11-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministradorTorneos', '0003_auto_20201102_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartermatch',
            name='matchNumber',
            field=models.PositiveIntegerField(),
        ),
    ]
