# Generated by Django 2.2 on 2020-10-31 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdministradorTorneos', '0003_auto_20201031_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmatch',
            name='loser',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalmatch_loser', to='AdministradorTorneos.Player'),
        ),
        migrations.AlterField(
            model_name='finalmatch',
            name='losing_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalmatch',
            name='match_players',
            field=models.ManyToManyField(blank=True, null=True, to='AdministradorTorneos.Player'),
        ),
        migrations.AlterField(
            model_name='finalmatch',
            name='winner',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalmatch_winner', to='AdministradorTorneos.Player'),
        ),
        migrations.AlterField(
            model_name='finalmatch',
            name='winning_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartermatch',
            name='loser',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quartermatch_loser', to='AdministradorTorneos.Player'),
        ),
        migrations.AlterField(
            model_name='quartermatch',
            name='losing_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartermatch',
            name='match_players',
            field=models.ManyToManyField(blank=True, null=True, to='AdministradorTorneos.Player'),
        ),
        migrations.AlterField(
            model_name='quartermatch',
            name='winner',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quartermatch_winner', to='AdministradorTorneos.Player'),
        ),
        migrations.AlterField(
            model_name='quartermatch',
            name='winning_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semimatch',
            name='loser',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semimatch_loser', to='AdministradorTorneos.Player'),
        ),
        migrations.AlterField(
            model_name='semimatch',
            name='losing_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semimatch',
            name='match_players',
            field=models.ManyToManyField(blank=True, null=True, to='AdministradorTorneos.Player'),
        ),
        migrations.AlterField(
            model_name='semimatch',
            name='winner',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semimatch_winner', to='AdministradorTorneos.Player'),
        ),
        migrations.AlterField(
            model_name='semimatch',
            name='winning_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
