# Generated by Django 2.2 on 2020-10-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministradorTorneos', '0004_auto_20201031_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmatch',
            name='match_players',
            field=models.ManyToManyField(blank=True, to='AdministradorTorneos.Player'),
        ),
        migrations.AlterField(
            model_name='quartermatch',
            name='match_players',
            field=models.ManyToManyField(blank=True, to='AdministradorTorneos.Player'),
        ),
        migrations.AlterField(
            model_name='semimatch',
            name='match_players',
            field=models.ManyToManyField(blank=True, to='AdministradorTorneos.Player'),
        ),
    ]
