# Generated by Django 2.2 on 2020-10-31 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdministradorTorneos', '0005_auto_20201031_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarterfinal',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='semifinal',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='quartermatch',
            name='quarterFinal',
        ),
        migrations.RemoveField(
            model_name='semimatch',
            name='semiFinal',
        ),
        migrations.AddField(
            model_name='quartermatch',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdministradorTorneos.Tournament'),
        ),
        migrations.AddField(
            model_name='semimatch',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdministradorTorneos.Tournament'),
        ),
        migrations.AlterField(
            model_name='finalmatch',
            name='final',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdministradorTorneos.Tournament'),
        ),
        migrations.DeleteModel(
            name='Final',
        ),
        migrations.DeleteModel(
            name='QuarterFinal',
        ),
        migrations.DeleteModel(
            name='SemiFinal',
        ),
    ]
