# Generated by Django 2.2 on 2020-11-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministradorTorneos', '0010_auto_20201113_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
