# Generated by Django 2.2 on 2020-11-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministradorTorneos', '0012_semimatch_qmfinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalmatch',
            name='SmFinished',
            field=models.BooleanField(default=False),
        ),
    ]
