# Generated by Django 2.2 on 2020-11-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministradorTorneos', '0013_finalmatch_smfinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartermatch',
            name='InscriptionFinished',
            field=models.BooleanField(default=False),
        ),
    ]
